name: Deploy React to cPanel

on:
  push:
    branches:
      - master  # Adjust this if your main branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Use the version your project requires

    - name: Install dependencies
      run: npm install
      env:
        CI: false  # Sometimes needed to bypass certain CI environment checks in scripts

    - name: Build project
      run: npm run build

    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.thezentrox.com
        username: deploy@thezentrox.com
        password: Deploy@#123@3
        local-dir: build
        server-dir: /public_html/thezentrox.com  # Adjust this to your public directory
